OPENAI_API_KEY = "OPENAI_API_KEY"

#Google Custom Search API keys
GCS_DEVELOPER_KEY = "GCS_DEVELOPER_KEY"
GCS_CX = "GCS_CX"

IMAGE_SIZE = 800
FPS = 24
NUMBER_OF_IMAGES= 2

GENERATED_MEDIA_FOLDER = "generated_media"